[package]
name = "mermaid"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
regex = "1.10"
mermaid-rs = "0.1.1"  # latest version
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"